export enum HeaderNames {
  'Name' = 'Name',
  'Date' = 'Date',
  'Notes' = 'Notes',
  'Real World Coordinates' = 'Real World Coordinates',
  'Latitude' = 'Latitude',
  'Longitude' = 'Longitude',
  'Altitude(m)' = 'Altitude(m)',
  'Planar Orientation Strike' = 'Planar Orientation Strike',
  'Planar Orientation Dip' = 'Planar Orientation Dip',
  'Planar Orientation Planar Feature Type' = 'Planar Orientation Planar Feature Type',
  'Planar Orientation Quality' = 'Planar Orientation Quality',
  'Planar Orientation Facing' = 'Planar Orientation Facing',
  'Planar Orientation Label' = 'Planar Orientation Label',
  'Linear Orientation Trend' = 'Linear Orientation Trend',
  'Linear Orientation Plunge' = 'Linear Orientation Plunge',
  'Linear Orientation Linear Feature Type' = 'Linear Orientation Linear Feature Type',
  'Trace Trace Quality' = 'Trace Trace Quality',
  'Trace Trace Type' = 'Trace Trace Type',
  'Trace Tace Notes' = 'Trace Tace Notes',
}
