export enum HeaderNames {
  'Name',
  'Date',
  'Self',
  'Notes',
  'Real World Coordinates',
  'Pixel Coordinates',
  'Latitude',
  'Longitude',
  'Altitude(m)',
  'Planar Orientation Strike',
  'Planar Orientation Dip',
  'Planar Orientation Planar Feature Type',
  'Planar Orientation Quality',
  'Planar Orientation Facing',
  'Linear Orientation Trend',
  'Linear Orientation Plunge',
  'Linear Orientation Linear Feature Type',
  'Planar Orientation Label',
  'Trace Trace Feature',
  'Trace Trace Quality',
  'Trace Trace Type',
  'Trace Other Feature',
  'Symbol Color',
  'Tag'
}
